/******************************************************************************
The MIT License (MIT)

Copyright (c) 2016 Matchbox Mobile Limited <info@matchboxmobile.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*******************************************************************************/

// This file was generated by Bluetooth (R) Developer Studio on 2016.03.17 21:39
// with plugin Windows 10 UWP Client (version 1.0.0 released on 2016.03.16).
// Plugin developed by Matchbox Mobile Limited.

using Wwssi.Bluetooth.HeartRateMonitor.Base;

namespace Wwssi.Bluetooth.HeartRateMonitor.HeartRate
{
    public class BleDeviceInformationService : BleService
    {
        /// <summary>
        /// Manufacturer Name String characteristic.
        /// </summary>
        public BleCharacteristic ManufacturerNameString { get; set; } = new BleCharacteristic("Manufacturer Name String", "2A29", false);  
        
        /// <summary>
        /// Model Number String characteristic.
        /// </summary>
        public BleCharacteristic ModelNumberString { get; set; } = new BleCharacteristic("Model Number String", "2A24", false);  
        
        /// <summary>
        /// Serial Number String characteristic.
        /// </summary>
        public BleCharacteristic SerialNumberString { get; set; } = new BleCharacteristic("Serial Number String", "2A25", false);  
        
        /// <summary>
        /// Hardware Revision String characteristic.
        /// </summary>
        public BleCharacteristic HardwareRevisionString { get; set; } = new BleCharacteristic("Hardware Revision String", "2A27", false);  
        
        /// <summary>
        /// Firmware Revision String characteristic.
        /// </summary>
        public BleCharacteristic FirmwareRevisionString { get; set; } = new BleCharacteristic("Firmware Revision String", "2A26", false);  
        
        /// <summary>
        /// Software Revision String characteristic.
        /// </summary>
        public BleCharacteristic SoftwareRevisionString { get; set; } = new BleCharacteristic("Software Revision String", "2A28", false);  
        
        /// <summary>
        /// System ID characteristic.
        /// </summary>
        public BleCharacteristic SystemID { get; set; } = new BleCharacteristic("System ID", "2A23", false);  
        
        /// <summary>
        /// IEEE 11073-20601 Regulatory Certification Data List characteristic.
        /// </summary>
        public BleCharacteristic IEEE1107320601RegulatoryCertificationDataList { get; set; } = new BleCharacteristic("IEEE 11073-20601 Regulatory Certification Data List", "2A2A", false);  
        
        /// <summary>
        /// PnP ID characteristic.
        /// </summary>
        public BleCharacteristic PnPID { get; set; } = new BleCharacteristic("PnP ID", "2A50", false);  
        
        private const bool IsServiceMandatory = true;

        public BleDeviceInformationService() : base("180A", IsServiceMandatory)
        {
        }
    }
}
